// pages/dashboard.vue
<template>
  <div v-if="!loading">
    <Verify v-if="user.user.discordId === null" />
    <Dashboard v-else :user="user" />
  </div>
  <div v-else class="header" />
</template>

<script>
export default {
    data () {
        return {
            loading: true,
            user: {}
        }
    },
    created () {
        if (process.client) {
            const spinner = this.$vs.loading({
                color: 'danger',
                background: '#050506'
            })
            this.$axios.get('http://localhost:3000/api/users/@me', { withCredentials: true })
                .then((res) => {
                    if (res.data) {
                        this.user = res.data
                        setTimeout(() => {
                            spinner.close()
                            this.loading = false
                        }, 800)
                    } else {
                        setTimeout(() => {
                            spinner.close()
                            this.$router.push('/')
                        }, 800)
                    }
                }).catch(() => {
                    setTimeout(() => {
                        spinner.close()
                        this.$router.push('/')
                    }, 800)
                })
        } else {
            this.$router.push('/')
        }
    }
}
</script>

// pages/dashboard.tsx
import Axios from 'axios';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { Spin } from 'antd';
import { LoadingOutlined } from '@ant-design/icons';
import styles from '../styles/main.module.css';
import VerifyComponent from '../components/verify';
import DashboardComponent from '../components/dashboard';

interface InitialState {
  user: any;
  images: any,
  loading: boolean;
}

const initialState = {
  user: {},
  images: [],
  loading: true,
};

export default function Dashboard() {
  const [{ user, loading, images }, setState] = useState<InitialState>(initialState);
  const router = useRouter();

  useEffect(() => {
    Axios.get('http://localhost:3001/users/@me', {
      withCredentials: true,
    })
      .then(({ data }) => {
        Axios.get(`http://localhost:3001/users/${data._id}/images`, {
          withCredentials: true,
        })
          .then((res) => {
            setTimeout(() => {
              setState((state) => ({ ...state, loading: false, user: data, images: res.data.images }));
            }, 1000);
          });
      })
      .catch(() => {
        router.push('/');
      });
  }, []);

  const spinner = (
    <LoadingOutlined style={{ fontSize: 40, color: 'white' }} spin />
  );

  if (loading)
    return (
      <div className={styles.container}>
        <Spin indicator={spinner} />
      </div>
    );

  return user.discord.id === null ? (
    <VerifyComponent />
  ) : (
    <DashboardComponent userProp={user} imagesProp={images} router={router} />
  );
}
